### ISSUE TITLE
Angular Cache with Angular 2

### ISSUE THREAD

**Issue by demisx** [jmdobry/angular-cache#233] opened 2016-08-15 21:20 UTC
Can angular-cache be used with Angular 2? Are there any examples by any chance? Thank you.

**Comment by jmdobry** [comment] 2016-08-16 17:19
Duplicate of #222

**Closed by jmdobry** 2016-08-16 17:19 UTC
Labels: duplicate

**Comment by demisx** [comment] 2016-08-16 17:22
My appologies. Not sure how I missed that. Thank you.
